version: "3.9"

networks:
  tarea2net:
    external: true

services:
  app:
    image: distnode
    container_name: ${NODE_NAME}
    environment:
      - KNOWN_NODE_IP
      - KNOWN_NODE_PORT
      - NODE_IP
      - NODE_PORT
      - NODE_ADDR
      - NODE_NAME
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    volumes:
      - ./protocol:/code/protocol
    command: "uvicorn protocol.main:app --host 0.0.0.0 --port ${NODE_PORT}"
    networks:
      tarea2net:
        ipv4_address: ${NODE_IP}
volumes:
  protocol:
